#!/usr/bin/env bash
# build_bundle.sh — package repo + credentials + app password into a single
# self-installing shell script. Run this on your laptop after you have the
# OAuth credentials and token.
#
# Usage:
#   bash scripts/build_bundle.sh \
#     --credentials path/to/credentials.json \
#     --token       path/to/token.json \
#     --app-password "xxxx xxxx xxxx xxxx" \
#     > sn2_install.sh
#
# Then deploy on the robot in *one* command:
#   ssh rainbow@<robot> 'bash -s' < sn2_install.sh
#
# Or copy + run:
#   scp sn2_install.sh rainbow@<robot>:
#   ssh rainbow@<robot> 'bash sn2_install.sh'

set -euo pipefail

usage() {
    sed -n '2,18p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
}

CREDS=""; TOKEN=""; PW=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --credentials)   CREDS="$2"; shift 2 ;;
        --token)         TOKEN="$2"; shift 2 ;;
        --app-password)  PW="$2"; shift 2 ;;
        -h|--help)       usage; exit 0 ;;
        *)               echo "unknown arg: $1" >&2; usage >&2; exit 2 ;;
    esac
done

err() { echo "build_bundle: $*" >&2; }

[[ -n "$CREDS" ]] || { err "missing --credentials"; exit 2; }
[[ -n "$TOKEN" ]] || { err "missing --token"; exit 2; }
[[ -n "$PW"    ]] || { err "missing --app-password"; exit 2; }
[[ -f "$CREDS" ]] || { err "file not found: $CREDS"; exit 2; }
[[ -f "$TOKEN" ]] || { err "file not found: $TOKEN"; exit 2; }

PW_CLEAN="${PW// /}"
if [[ ${#PW_CLEAN} -ne 16 || ! "$PW_CLEAN" =~ ^[a-zA-Z0-9]+$ ]]; then
    err "app password must be 16 alphanumeric characters after stripping spaces (got ${#PW_CLEAN})"
    exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# base64-encode credentials (sidestep heredoc edge cases entirely)
CREDS_B64=$(base64 -w0 "$CREDS")
TOKEN_B64=$(base64 -w0 "$TOKEN")

# repo tarball (skip local-only / generated stuff)
TAR_B64=$(
    tar -C "$REPO_ROOT" \
        --exclude='./.git' \
        --exclude='./.venv' \
        --exclude='./venv' \
        --exclude='./.pytest_cache' \
        --exclude='./__pycache__' \
        --exclude='./*/__pycache__' \
        --exclude='./*/*/__pycache__' \
        --exclude='./*.egg-info' \
        --exclude='./*/*.egg-info' \
        --exclude='./build' \
        --exclude='./dist' \
        --exclude='./.claude' \
        --exclude='./sn2_install.sh' \
        -czf - . | base64 -w0
)

err "bundle size: ~$(printf '%s\n' "$TAR_B64" | wc -c | awk '{printf "%.0fKB", $1/1024}') (compressed+b64)"

# ---- emit self-installing script ----
# IMPORTANT: outer heredoc is UNQUOTED so the *_B64 variables are expanded at
# build time. The inner robot-side commands must escape any $ they want
# evaluated at run time as `\$`.
cat <<INSTALLER
#!/usr/bin/env bash
# sn2_backup self-installing bundle (generated by scripts/build_bundle.sh)
set -euo pipefail

if [[ -t 1 ]]; then
    BLD=\$'\\033[1m'; GRN=\$'\\033[0;32m'; NC=\$'\\033[0m'
else
    BLD=''; GRN=''; NC=''
fi
log()  { printf "%b[ok ]%b %s\\n" "\$GRN" "\$NC" "\$*"; }
step() { printf "\\n%b==> %s%b\\n" "\$BLD" "\$*" "\$NC"; }

if [[ "\$EUID" -eq 0 ]]; then
    echo "do not run as root" >&2
    exit 1
fi

SN2_DIR="\$HOME/.sn2_backup"
REPO_DIR="\$HOME/ws/data_manager"

step "Writing credentials to \$SN2_DIR"
mkdir -p "\$SN2_DIR"
chmod 700 "\$SN2_DIR"

umask 077
echo '$CREDS_B64' | base64 -d > "\$SN2_DIR/credentials.json"
echo '$TOKEN_B64' | base64 -d > "\$SN2_DIR/token.json"
printf 'SN2_BACKUP_APP_PASSWORD=%s\\n' '$PW_CLEAN' > "\$SN2_DIR/env"
chmod 600 "\$SN2_DIR/credentials.json" "\$SN2_DIR/token.json" "\$SN2_DIR/env"
log "credentials.json, token.json, env"

step "Extracting repo to \$REPO_DIR"
mkdir -p "\$(dirname "\$REPO_DIR")"
if [[ -d "\$REPO_DIR" ]]; then
    echo "[info] backing up existing \$REPO_DIR -> \$REPO_DIR.bak.\$(date +%s)"
    mv "\$REPO_DIR" "\$REPO_DIR.bak.\$(date +%s)"
fi
mkdir -p "\$REPO_DIR"
echo '$TAR_B64' | base64 -d | tar -C "\$REPO_DIR" -xzf -
log "extracted to \$REPO_DIR"

step "Handing off to install_on_robot.sh"
exec bash "\$REPO_DIR/scripts/install_on_robot.sh"
INSTALLER
